#
###################################
# Site wide configuration
####################################
#
title: David Romero
email: davromalc@gmail.com
description: My personal website.
url: https://david-romero.github.io/ # the base hostname & protocol for your site
keywords: ["Programming", "Java", "Spring", "Docker", "Kotlin", "Testing", "Clean code", "Scala", "Software Development"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Madrid
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: David Romero
  avatar: david-romero-github.jpeg
  job: "Software Engineer"
  bio: "For several years I have a hard goal. I want to become a great software engineer, so I work hard developing quality
software every day. Fan of new technologies. I will not stop until overcome my goals."
  email: davromalc@gmail.com
  disqus-shortname: 
  twitter: davromalc #username
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: david-romero #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: davidromeroalcaide #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
